### ISSUE TITLE
License headers needs to be updated

### ISSUE THREAD

**Issue by TimKack** [tunnelvisionlabs/goworks#6]
It seems that the license blurb in the individual source files contradicts the project license text.
Here is a sample:

```
/*
 *  Copyright (c) 2012 Sam Harwell, Tunnel Vision Laboratories LLC
 *  All rights reserved.
 * 
 *  The source code of this document is proprietary work, and is not licensed for
 *  distribution. For information about licensing, contact Sam Harwell at:
 *      sam@tunnelvisionlabs.com
 */
```

This is problematic if I want to try to sort out the build failures on NB 8.1  - I do not want to sign CONTRIBUTING until I understand what license the project is under :)

**Comment by sharwell** [comment]
For the time being, this license header is correct. Due to IP issues which we've been unable to resolve so far, this project would be considered more "source open" than "open source". The contributor agreement exists only as a way for users who make no ownership claims to provide, with no strings attached, code back to a project which would not be considered open source.
